# Generated by Django 5.2.6 on 2025-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit for the task in minutes', null=True),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
