# Generated by Django 5.2.6 on 2025-10-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_due_date_task_time_limit_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='taskcompletion',
            name='performance_delta',
        ),
        migrations.AddField(
            model_name='user',
            name='membership_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='player_id',
            field=models.CharField(blank=True, help_text='Unique ID for players', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('management', 'Management'), ('coach', 'Coach'), ('player', 'Player'), ('parent', 'Parent')], default='player', max_length=20),
        ),
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.OneToOneField(limit_choices_to={'role': 'player'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_link', to=settings.AUTH_USER_MODEL)),
                ('parent', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='child_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
