from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    RegisterView,
    ParentRegisterView,
    ProfileViewSet,
    AcademyViewSet,
    UserViewSet,
    TaskViewSet,
    my_tasks,
    coach_mark_task_complete,
    player_start_task,
    parent_dashboard
)

# The router automatically generates the standard URLs for our ViewSets
# (e.g., list, create, retrieve, update, delete)
router = DefaultRouter()
router.register('users', UserViewSet, basename='user')
router.register('profiles', ProfileViewSet, basename='profile')
router.register('academies', AcademyViewSet, basename='academy')
router.register('tasks', TaskViewSet, basename='task')

# The urlpatterns list maps specific URL endpoints to our custom views
urlpatterns = [
    # Includes all the URLs generated by the router (e.g., /api/tasks/, /api/users/1/)
    path('', include(router.urls)),

    # Custom URLs for different types of registration
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/register/parent/', ParentRegisterView.as_view(), name='parent-register'),

    # Custom URLs for specific dashboard actions
    path('player/my-tasks/', my_tasks, name='my-tasks'),
    path('player/tasks/<int:task_id>/start/', player_start_task, name='player-start-task'),
    path('coach/tasks/<int:task_id>/player/<int:player_id>/complete/', coach_mark_task_complete, name='coach-mark-task-complete'),
    path('parent/dashboard/', parent_dashboard, name='parent-dashboard'),
]
